<!doctype html>
<!--[if lt IE 7]><html class="ie6 oldie"> <![endif]-->
<!--[if IE 7]><html class="ie7 oldie"> <![endif]-->
<!--[if IE 8]><html class="ie8 oldie"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="">
<!--<![endif]-->
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>The Projector</title>
<link href="_css/boilerplate.css" rel="stylesheet" type="text/css"/>
<link href="_css/Root_Project.css" rel="stylesheet" type="text/css"/>
<link href="_css/main.css" rel="stylesheet" type="text/css"/>	

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script src="_scripts/respond.min.js"></script>

</head>
<body>

    <div class="gridContainer clearfix"> 
      <div class="ProjGalleryBackgroundDiv">
      
      <!-- HEADER AND NAVIGATION --------------------------------------------->
        <?php $selectedNav = ""; ?>
		<?php include("HeaderNav.php"); ?>
        <div id="NavShadowDiv"></div> 
        <!-- PAGE CONTENT --------------------------------------------->
        <div id="ContentDiv">
        
         <div id="GalleryDetailPageTitle">
           <h1>Terms and Conditions</h1>
           
         </div>
         
       	  <!-- SUMMARY --------------------------------------------->
		  <div>
		    <p><strong>Terms of Use Agreement and Copyright License</strong><br>
		      Effective Date:&nbsp; This Terms of Use Agreement was last updated on October 8, 2012.<br>
	        This Terms of Use Agreement sets forth the standards of use of the Pearson Foundation Learning Labs Projector website owned by Pearson Foundation, located at <strong>http://pfprojector.org</strong> (the "Website") and the educational projects offered by Pearson Foundation on the Website in the Project Gallery (the "Projects").  By using the Website and/or the Projects, You agree to these terms and conditions. If you do not agree to the terms and conditions of this agreement, you should immediately cease all usage of the Website and Projects. Pearson Foundation reserves the right, at any time, to modify, alter, or update the terms and conditions of this agreement without prior notice.&nbsp; Modifications shall become effective immediately upon being posted on the Website.&nbsp; Your continued use of the Website or Projects after amendments are posted constitutes an acknowledgement and acceptance of the Agreement and its modifications. Except as provided in this paragraph, this Agreement may not be amended.</p>
		    <p><br>
		      <strong>1. Disclaimer of Warranties.</strong></p>
		    <p>THE WEBSITE IS PROVIDED BY PEARSON FOUNDATION ON AN "AS IS" AND ON AN  "AS AVAILABLE" BASIS.&nbsp; TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, PEARSON FOUNDATION MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, REGARDING THE PROJECTS, THE WEBSITE OR THE INFORMATION CONTAINED ON THE WEBSITE.  PEARSON FOUNDATION SHALL HAVE NO LIABILITY FOR ANY INTERRUPTIONS IN ACCESS TO THE PROJECTS OR IN THE USE OF THE WEBSITE. PEARSON FOUNDATION DISCLAIMS ALL WARRANTIES WITH REGARD TO THE PROJECTS, THE WEBSITE AND INFORMATION CONTAINED ON THE WEBSITE, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.&nbsp; SOME JURISDICTIONS DO NO ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, THEREFORE THE ABOVE-REFERENCED EXCLUSION IS INAPPLICABLE IN SUCH JURISDICTIONS.</p>
		    <p><br>
		      <strong>2. Limitation of Liability</strong><br>
	        PEARSON FOUNDATION SHALL NOT BE LIABLE FOR ANY DAMAGES WHATSOEVER, AND IN PARTICULAR PEARSON FOUNDATION SHALL NOT BE LIABLE FOR ANY SPECIAL, INDIRECT, CONSEQUENTIAL, OR INCIDENTAL DAMAGES, OR DAMAGES FOR LOST PROFITS, LOSS OF REVENUE, OR LOSS OF USE, ARISING OUT OF OR RELATED TO THE PROJECTS, THE WEBSITE OR THE INFORMATION CONTAINED ON THE WEBSITE, WHETHER SUCH DAMAGES ARISE IN CONTRACT, NEGLIGENCE, TORT, UNDER STATUTE, IN EQUITY, AT LAW, OR OTHERWISE, EVEN IF PEARSON FOUNDATION HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.  SOME JURISDICTIONS DO NOT ALLOW FOR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES, THEREFORE SOME OF THE ABOVE LIMITATIONS ARE INAPPLICABLE IN SUCH JURISDICTIONS. </p>
		    <p><br>
		      <strong>3. Indemnification</strong><br>
		      You agree to indemnify and hold Pearson Foundation, its parents, subsidiaries, affiliates, officers, directors and employees, harmless from any claim or demand, including reasonable attorneys' fees and costs, made by any third party due to or arising out of Your use of the Projects, the Website, or information contained on the Website, the violation of this Agreement, or infringement by You, or any other user of the Projects or the Website using Your computer, of any intellectual property or any other right of any person or entity. </p>
		    <p><br>
		      <strong>4. Modifications and Interruption to Service</strong><br>
		      Pearson Foundation reserves the right to modify or discontinue one or more of the Projects or the Website with or without notice to You. Pearson Foundation shall not be liable to You or any third party should Pearson Foundation exercise its right to modify or discontinue the Projects or the Website.  You acknowledge and accept that Pearson Foundation does not guarantee continuous, uninterrupted or secure access to the Website and operation of the Website may be interfered with or adversely affected by numerous factors or circumstances, including, but not limited to, Acts of God. </p>
		    <p><br>
		      <strong>5. Third-Party Websites</strong><br>
		      The Website may include references to content hosted on other websites and/or links to other websites that are owned and/or operated by third parties.&nbsp; You acknowledge that Pearson Foundation is not responsible for the availability of, or the content located on or through, any third-party website.&nbsp; You should contact the site administrator or webmaster for those third-party websites if You have any concerns regarding such links or the content located on such websites.&nbsp; Your use of those third-party websites is subject to the terms of use and privacy policies of each website. Pearson Foundation is not responsible for the use of such websites, and makes no representations that use of the content hosted on such third-party websites will not infringe the intellectual property rights of any third parties.  Pearson Foundation encourages You to review terms of use and privacy policies of any third-party websites and to make your own determination with respect to the use of intellectual property owned by any third parties in connection with your implementation of the Projects.</p>
		    <p><br>
		      <strong>6. Copyright and Trademark Information </strong><br>
		      Content included or available on the Website, other than the content contained in the Project Gallery, including site design, logo, text, graphics, interfaces, and the selection and arrangements thereof is ©2012 Pearson Foundation, and Pearson Foundation reserves all rights with respect to this content. All content contained in the Project Gallery is licensed for use pursuant to the Copyright License in Section 11.<br>
		      Pearson Foundation Learning Labs Projector and the name Pearson Foundation are the proprietary trademarks of Pearson Foundation.&nbsp; Except as required below in order to give proper attribution, Pearson Foundation's marks may not be used in connection with any product or service in any manner that is likely to cause confusion among the general public without prior written permission of an authorized officer of Pearson Foundation, or in any manner that disparages or discredits Pearson Foundation.</p>
		    <p><br>
		      <strong>7. Disclaimer Regarding Accuracy of Project Information and Your Implementation of Projects</strong><br>
		      All Projects appearing on the Website have been  reviewed, edited, and produced by Pearson Foundation staff and key partners, and have been tested in a minimum of five classrooms in a series of pilot tests. Pearson Foundation has made every effort to ensure the quality and accuracy of the Projects, however, Pearson Foundation can make no representations or warranties as to the accuracy or reliability of the information presented in the Challenge Details or Teacher Notes, and can make no representations or warranties as to the results that You, Your students, or any person using the Project content may obtain in implementing any of the Projects in whole or in part, or in using any of the content available in the Project Gallery in any manner.</p>
		    <p><br>
		      <strong>8. Governing Jurisdiction of the Courts</strong><br>
		      You acknowledges and agrees that these Terms of Use are governed by the laws of the State of California, without giving effect to any choice of law rules.&nbsp; Pearson Foundation makes no representation that the Website or Services are legal or available for use in other locations.&nbsp;  You also acknowledge and agree that any legal action or lawsuit arising from these Terms of Use or Pearson Foundation's <a href="http://www.pearsonfoundation.org/oecd/privacy.html">Privacy Statement</a> must be brought only in a State or Federal Court in the State of California, United States.&nbsp;</p>
		    <p><br>
		      <strong>9. Compliance with Laws.</strong><br>
		      You are responsible for knowledge of and compliance with all applicable laws.&nbsp; You may not use the Projects or the Website in any way that violates applicable state, federal, or international laws, regulations or other government requirements.  You further agree not to transmit any material that may constitute a criminal offense, give rise to civil liability or otherwise violate any applicable local, state, national, or international law or regulation. </p>
		    <p><br>
		      <strong>10. Other Terms</strong><br>
		      If any provision of this Terms of Use Agreement shall be unlawful, void or unenforceable for any reason, the other provisions (and any partially-enforceable provision) shall not be affected thereby and shall remain valid and enforceable to the maximum possible extent permitted by law.&nbsp;</p>
		    <p><br>
		      You agree that this Terms of Use Agreement and any other agreements referenced herein may be assigned by Pearson Foundation in its sole discretion, to a third party in the event of a merger or acquisition.&nbsp; You agree that by accepting this Terms of Use Agreement, You are consenting to the use and disclosure of Your personally identifiable information and other practices described in our Privacy Policy Statement.</p>
		    <p><br>
		      <strong>11. Copyright License</strong><br>
		      PEARSON FOUNDATION HEREBY PROVIDES THE PROJECT CONTENT UNDER THE TERMS OF THIS LICENSE (&quot;LICENSE&quot;). THE PROJECT CONTENT IS PROTECTED BY COPYRIGHT AND/OR OTHER APPLICABLE LAW. ANY USE OF THE PROJECT CONTENT OTHER THAN AS AUTHORIZED UNDER THIS LICENSE OR COPYRIGHT LAW IS PROHIBITED.<br>
		      BY EXERCISING ANY RIGHTS TO THE PROJECT CONTENT PROVIDED HERE, YOU ACCEPT AND AGREE TO BE BOUND BY THE TERMS OF THIS LICENSE. TO THE EXTENT THIS LICENSE MAY BE CONSIDERED TO BE A CONTRACT, THE PEARSON FOUNDATION GRANTS YOU THE RIGHTS CONTAINED HERE IN CONSIDERATION OF YOUR ACCEPTANCE OF SUCH TERMS AND CONDITIONS.</p>
		    <p><br>
		      <strong>1. Definitions</strong></p>
            <ol start="1" type="a">
              <li><strong>&quot;Adaptation&quot;</strong> means a work based upon the Project Content, or      upon the Project Content and other pre-existing works, such as a      translation, adaptation, derivative work, arrangement of music or other      alterations of a literary or artistic work, or phonogram or performance      and includes cinematographic adaptations or any other form in which the Project      Content may be recast, transformed, or adapted including in any form      recognizably derived from the original, except that a work that      constitutes a Collection will not be considered an Adaptation for the      purpose of this License. For the avoidance of doubt, where the Project      Content used is a musical work, performance or phonogram, the      synchronization of the Project Content in timed-relation with a moving      image (&quot;synching&quot;) will be considered an Adaptation for the      purpose of this License.</li>
              <li><strong>&quot;Collection&quot;</strong> means a collection of literary or artistic      works, such as encyclopedias and anthologies, or performances, phonograms      or broadcasts, or other works or subject matter other than works listed in      Section 1(g) below, which, by reason of the selection and arrangement of      their contents, constitute intellectual creations, in which the Project      Content is included in its entirety in unmodified form along with one or      more other contributions, each constituting separate and independent works      in themselves, which together are assembled into a collective whole. A      work that constitutes a Collection will not be considered an Adaptation      (as defined above) for the purposes of this License.</li>
              <li><strong>&quot;Distribute&quot;</strong> means to make available to the public the      original and copies of the Project Content or Adaptation, as appropriate,      through a transfer of ownership.</li>
              <li><strong>&quot;Project Content&quot;</strong> means the literary and/or artistic works made      available in digital form in the Project Gallery on the Website, which is      offered under the terms of this License including without limitation any      production in the literary, scientific and artistic domain, such as a      book, pamphlet and other writing; a lecture, address, sermon or other work      of the same nature; a dramatic or dramatico-musical work; a choreographic      work or entertainment in dumb show; a musical composition with or without      words; a cinematographic work to which are assimilated works expressed by      a process analogous to cinematography; a work of drawing, painting,      architecture, sculpture, engraving or lithography; a photographic work to      which are assimilated works expressed by a process analogous to      photography; a work of applied art; an illustration, map, plan, sketch or      three-dimensional work relative to geography, topography, architecture or      science; a performance; a broadcast; a phonogram; a compilation of data to      the extent it is protected as a copyrightable work; or a work performed by      a variety or circus performer to the extent it is not otherwise considered      a literary or artistic work.</li>
              <li><strong>&quot;You&quot;</strong> means an individual or entity exercising rights      under this License who has not previously violated the terms of this      License with respect to the Work, or who has received express permission      from Pearson Foundation to exercise rights under this License despite a      previous violation.</li>
              <li><strong>&quot;Publicly Perform&quot;</strong> means to perform public recitations of the Project      Content and to communicate to the public those public recitations, by any      means or process, including by wire or wireless means or public digital      performances; to make available to the public Project Content in such a      way that members of the public may access the Project Content from a place      and at a place individually chosen by them; to perform the Project Content      to the public by any means or process and the communication to the public      of the performances of the Project Content, including by public digital      performance; to broadcast and rebroadcast the Project Content by any means      including signs, sounds or images.</li>
              <li><strong>&quot;Reproduce&quot;</strong> means to make copies of the Project Content by      any means including without limitation by sound or visual recordings and      the right of fixation and reproducing fixations of the Project Content,      including storage of a protected performance or phonogram in digital form      or other electronic medium.</li>
            </ol>
            <p><strong>2. Fair Use Rights.</strong> Nothing in this License is intended to reduce, limit, or restrict any uses free from copyright or rights arising from limitations or exceptions that are provided for in connection with the copyright protection under copyright law or other applicable laws.<br>
              <strong>3. License Grant.</strong> Subject to the terms and conditions of this License, Pearson Foundation hereby grants You a worldwide, royalty-free, non-exclusive, perpetual (for the duration of the applicable copyright) license to exercise the rights in the Project Content as stated below:</p>
            <ol start="1" type="a">
              <li>to Reproduce the Project Content, to incorporate the Project      Content into one or more Collections, and to Reproduce the Project Content      as incorporated in the Collections;</li>
              <li>to create and Reproduce Adaptations provided that any such      Adaptation, including any translation in any medium, takes reasonable      steps to clearly label, demarcate or otherwise identify that changes were      made to the original Project Content. For example, a translation could be      marked &quot;The original work was translated from English to      Spanish,&quot; or a modification could indicate &quot;The original work      has been modified.&quot;;</li>
              <li>to Distribute, Display and Publicly Perform the Project Content including      as incorporated in Collections; and,</li>
              <li>to Distribute, Display and Publicly Perform Adaptations.</li>
            </ol>
            <p>The above rights may be exercised in all media and formats whether now known or hereafter devised. The above rights include the right to make such modifications as are technically necessary to exercise the rights in other media and formats. Subject to Section 8(f), all rights not expressly granted by Pearson Foundation are hereby reserved, including but not limited to the rights described in Section 4(e).</p>
            <p><br>
              <strong>4. Restrictions.</strong> The license granted in Section 3 above is expressly made subject to and limited by the following restrictions:</p>
            <ol start="1" type="a">
              <li>You may Distribute, Display or Publicly Perform the Work only      under the terms of this License. You must include a copy of this License      with every copy of the Work You Distribute, Display or Publicly Perform.      You may not offer or impose any terms on the Project Content that restrict      the terms of this License or the ability of the recipient of the Project      Content to exercise the rights granted to that recipient under the terms      of the License. You may not sublicense the Project Content. You must keep      intact all notices that refer to this License and to the disclaimer of      warranties with every copy of the Project Content You Distribute, Display      or Publicly Perform. When You Distribute, Display or Publicly Perform the      Work, You may not impose any effective technological measures on the Work      that restrict the ability of a recipient of the Project Content from You      to exercise the rights granted to that recipient under the terms of the      License. This Section 4(a) applies to the Project Content as incorporated      in a Collection, but this does not require the Collection apart from the Project      Content itself to be made subject to the terms of this License. If You      create a Collection, upon notice from Pearson Foundation, You must, to the      extent practicable, remove from the Collection any credit as required by      Section 4(d), as requested. If You create an Adaptation, upon notice from Pearson      Foundation You must, to the extent practicable, remove from the Adaptation      any credit as required by Section 4(d), as requested.</li>
              <li>You may Distribute, Display or Publicly Perform an Adaptation only      under the terms of this License. You must include a copy of this License with      every copy of each Adaptation You Distribute, Display or Publicly Perform.      You may not offer or impose any terms on the Adaptation that restrict the      terms of the License or the ability of the recipient of the Adaptation to      exercise the rights granted to that recipient under the terms of the      License. You must keep intact all notices that refer to the License and to      the disclaimer of warranties with every copy of the Project Content as      included in the Adaptation You Distribute, Display or Publicly Perform.      When You Distribute, Display or Publicly Perform the Adaptation, You may      not impose any effective technological measures on the Adaptation that      restrict the ability of a recipient of the Adaptation from You to exercise      the rights granted to that recipient under the terms of the License. This      Section 4(b) applies to the Adaptation as incorporated in a Collection,      but this does not require the Collection apart from the Adaptation itself      to be made subject to the terms of the License.</li>
              <li>You may not exercise any of the rights granted to You in Section 3      above in any manner that is primarily intended for or directed toward      commercial advantage or private monetary compensation, and you may not      offer to sell the Project Content or any Adaption. The exchange of the Project      Content for other copyrighted works by means of digital file-sharing or      otherwise shall not be considered to be intended for or directed toward      commercial advantage or private monetary compensation, provided there is      no payment of any monetary compensation in connection with the exchange of      copyrighted works.</li>
              <li>If You Distribute, Display or Publicly Perform the Project Content      or any Adaptations or Collections, You must, unless a request has been      made pursuant to Section 4(a), keep intact all copyright notices for the Project      Content and provide, reasonable to the medium or means You are utilizing:      (i) the following statement, "This lesson is made available through the      efforts of the Pearson Foundation"; and (ii) consistent with Section 3(b),      in the case of an Adaptation, a credit identifying the use of the Project      Content in the Adaptation (e.g., &quot;French translation of the Project      Content made available by Pearson Foundation&quot;). The credit required      by this Section 4(d) may be implemented in any reasonable manner;      provided, however, that in the case of an Adaptation or Collection, at a      minimum such credit will appear, if a credit for all contributing authors      of the Adaptation or Collection appears, then as part of these credits and      in a manner at least as prominent as the credits for the other      contributing authors. For the avoidance of doubt, You may only use the      credit required by this Section for the purpose of attribution in the      manner set out above and, by exercising Your rights under this License,      You may not implicitly or explicitly assert or imply any connection with,      sponsorship or endorsement by Pearson Foundation, as appropriate, of You      or Your use of the Work, without the separate, express prior written      permission of Pearson Foundation.</li>
            </ol>
            <ol>
              <li>For the avoidance of doubt:</li>
            </ol>
            <ol start="5" type="a">
              <ol start="1" type="i">
                <li><strong>Non-waivable Compulsory License Schemes</strong>. In those jurisdictions in which the right to       collect royalties through any statutory or compulsory licensing scheme       cannot be waived, Pearson Foundation reserves the exclusive right to       collect such royalties for any exercise by You of the rights granted       under this License;</li>
                <li><strong>Waivable Compulsory License Schemes</strong>. In those jurisdictions in which the right to       collect royalties through any statutory or compulsory licensing scheme       can be waived, Pearson Foundation reserves the exclusive right to collect       such royalties for any exercise by You of the rights granted under this       License if Your exercise of such rights is for a purpose or use which is       otherwise than noncommercial as permitted under Section 4(c) and       otherwise waives the right to collect royalties through any statutory or       compulsory licensing scheme; and,</li>
                <li><strong>Voluntary License Schemes</strong>. Pearson Foundation reserves the right to       collect royalties, whether individually or, in the event that Pearson       Foundation is a member of a collecting society that administers voluntary       licensing schemes, via that society, from any exercise by You of the       rights granted under this License that is for a purpose or use which is       otherwise than noncommercial as permitted under Section 4(c).</li>
              </ol>
              <li>Except as otherwise agreed in writing by Pearson Foundation or as      may be otherwise permitted by applicable law, if You Reproduce, Distribute,      Display or Publicly Perform the Project Content either by itself or as      part of any Adaptations or Collections, You must not distort, mutilate,      modify or take other derogatory action in relation to the Work which would      be prejudicial to Pearson Foundation's honor or reputation. Pearson      Foundation agrees that in those jurisdictions (e.g. Japan), in which any      exercise of the right granted in Section 3(b) of this License (the right      to make Adaptations) would be deemed to be a distortion, mutilation,      modification or other derogatory action prejudicial to Pearson Foundation's      honor and reputation, Pearson Foundation will waive or not assert, as      appropriate, this Section, to the fullest extent permitted by the      applicable national law, to enable You to reasonably exercise Your right      under Section 3(b) of this License (right to make Adaptations) but not      otherwise. </li>
            </ol>
            <p><strong>5. Representations, Warranties and Disclaimer</strong> <br>
            UNLESS OTHERWISE MUTUALLY AGREED TO BY THE PARTIES IN WRITING AND TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, PEARSON FOUNDATION OFFERS THE PROJECT CONTENT AS-IS AND MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND CONCERNING THE PROJECT CONTENT, EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING, WITHOUT LIMITATION, WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NONINFRINGEMENT, OR THE ABSENCE OF LATENT OR OTHER DEFECTS, ACCURACY, OR THE PRESENCE OF ABSENCE OF ERRORS, WHETHER OR NOT DISCOVERABLE. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THIS EXCLUSION MAY NOT APPLY TO YOU.</p>
            <p><br>
              <strong>6. Limitation on Liability.</strong> EXCEPT TO THE EXTENT REQUIRED BY APPLICABLE LAW, IN NO EVENT WILL PEARSON FOUNDATION BE LIABLE TO YOU ON ANY LEGAL THEORY FOR ANY SPECIAL, INCIDENTAL, CONSEQUENTIAL, PUNITIVE OR EXEMPLARY DAMAGES ARISING OUT OF THIS LICENSE OR THE USE OF THE WORK, EVEN IF LICENSOR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
            <p><br>
              <strong>7. Termination</strong></p>
            <ol start="1" type="a">
              <li>This License and the rights granted hereunder will terminate      automatically upon any breach by You of the terms of this License.      Individuals or entities who have received Adaptations or Collections from      You under this License, however, will not have their licenses terminated      provided such individuals or entities remain in full compliance with those      licenses. Sections 1, 2, 5, 6, 7, and 8 will survive any termination of      this License.</li>
              <li>Subject to the above terms and conditions, the license granted      here is perpetual (for the duration of the applicable copyright in the      Work). Notwithstanding the above, Licensor reserves the right to release      the Work under different license terms or to stop distributing the Work at      any time; provided, however that any such election will not serve to      withdraw this License (or any other license that has been, or is required      to be, granted under the terms of this License), and this License will      continue in full force and effect unless terminated as stated above.</li>
            </ol>
            <p><strong>8. Miscellaneous</strong></p>
            <ol start="1" type="a">
              <li>Each time You Distribute, Display or Publicly Perform the Work or      a Collection, Pearson Foundation offers to the recipient a license to the Project      Content on the same terms and conditions as the license granted to You      under this License.</li>
              <li>Each time You Distribute, Display or Publicly Perform an      Adaptation, Pearson Foundation offers to the recipient a license to the      original Work on the same terms and conditions as the license granted to You      under this License.</li>
              <li>If any provision of this License is invalid or unenforceable under      applicable law, it shall not affect the validity or enforceability of the      remainder of the terms of this License, and without further action by the      parties to this agreement, such provision shall be reformed to the minimum      extent necessary to make such provision valid and enforceable.</li>
              <li>No term or provision of this License shall be deemed waived and no      breach consented to unless such waiver or consent shall be in writing and      signed by the party to be charged with such waiver or consent.</li>
              <li>This License constitutes the entire agreement between the parties      with respect to the Project Content licensed here. There are no      understandings, agreements or representations with respect to the Project      Content not specified here. Pearson Foundation shall not be bound by any      additional provisions that may appear in any communication from You. This      License may not be modified without the mutual written agreement of Pearson      Foundation and You.</li>
              <li>The rights granted under, and the subject matter referenced, in      this License were drafted utilizing the terminology of the Berne      Convention for the Protection of Literary and Artistic Works (as amended      on September 28, 1979), the Rome Convention of 1961, the WIPO Copyright      Treaty of 1996, the WIPO Performances and Phonograms Treaty of 1996 and      the Universal Copyright Convention (as revised on July 24, 1971). These      rights and subject matter take effect in the relevant jurisdiction in      which the License terms are sought to be enforced according to the      corresponding provisions of the implementation of those treaty provisions      in the applicable national law. If the standard suite of rights granted      under applicable copyright law includes additional rights not granted      under this License, such additional rights are deemed to be included in      the License; this License is not intended to restrict the license of any      rights under applicable law.</li>
            </ol>
            <p>&nbsp;</p>
		  </div>
          
           
       	  <!-- FOOTER ---------------------------------------------> 
            <div id="GeneralFooterDiv">
            <hr/>
            <a href="http://www.teachingawards.com/home" target="_blank"><img src="_images/logo_teachingawards.gif" alt="Pearson Teaching Awards"></a>
              <!--a href="http://www.si.edu" target="_blank"><img src="_images/logo_smithsonian.gif" alt="Smithsonian"></a-->
              <a href="http://www.pearsonfoundation.org" target="_blank"><img src="_images/logo_pearsonfound.gif" alt="Pearson Teaching Awards"></a>
              <a href="http://www.nationalmockelection.org" target="_blank"><img src="_images/logo_myvoice.gif" alt="My Voice My Election"></a>
              <p>© Pearson Foundation 2012 | <a href="mailto:labs@pearsonfoundation.org">Contact</a> | <a href="TermsConditions.php">Terms and Conditions</a></p>
        	</div>
        </div>
        
          
      </div>
      
    </div>
    
    
</body>
</html>
